ucs:
  systems:
  - password: xaog4W9GpYFH8zr+JwdEB2blgQUuMkQP
    url: 10.52.208.160
    username: admin
  - password: 3OnU53X9Ftxm4JNwpaC5kxhsTlmt
    url: 10.52.208.71
    username: admin
  - password: octDSUXb/jsLhk2PNs2GMV7zFQJmMUMs
    url: 10.52.208.120
    username: admin
